name: HelpfulPlayerCommands
main: com.yahoo.gamer66790.HPCCore
version: 1.0
commands:
    heal:
        description: This command heals you.
        usage: /heal
    feed:
        description: This command feeds and saturates you.
        usage: /feed
    poc:
        description: Grants you the power of creation.
        usage: /poc
    tts:
        description: Allows you to go to the sky.
        usage: /tts
        aliases: tothesky
    skull:
        description: Gives you specified player skull.
        usage: /skull <player name>
    killit:
        description: Kills the rain.
        usage: /killit
    tillik:
        description: Causes the rain.
        usage: /tillik
    playnice:
        description: Disables PvP in a world.
        usage: /playnice
    playmean:
        description: Enables PvP in a world.
        usage: /playmean
    hpcreload:
        description: Reloads HPC config
        usage: /hpcreload
    locate:
        description: Locates a specified player.
        usage: /locate <player name>
    echest:
        description: Opens the player's enderchest.
        usage: /echest